<?php
/**
 * TestLink Open Source Project - http://testlink.sourceforge.net/
 * This script is distributed under the GNU General Public License 2 or later.
 *
 * Constants and configuration parameters used throughout TestLink
 *
 * There are included extra files:
 * - your customized settings - custom_config.inc.php
 * - DB access - config_db.inc.php
 * - constants - const.inc.php
 * - basic checking - configCheck.php
 *
 * IMPORTANT:
 * To adapt values to your needs DO NOT EDIT THIS FILE but use custom_config.inc.php and
 * replace values of TestLink configuration variables.
 * It saves your changes for the next upgrade in one extra file.
 *
 * @filesource  config.inc.php
 * @package     TestLink
 * @copyright   2005-2022, TestLink community
 * @link        http://www.testlink.org
 *
 *
 **/

// Be sure you have all the environment variables defined in your docker-compose.yml

/** GUI themes (base for CSS and images)- modify if you create own one */
$tlCfg->theme_dir = 'gui/themes/' . getenv('THEME_DIR') . '/';

// SMTP server Configuration ("localhost" is enough in the most cases)
$g_smtp_host = getenv('SMTP_HOST'); # SMTP server MUST BE configured
$g_tl_admin_email = getenv('ADMIN_EMAIL'); # for problem/error notification
$g_from_email = getenv('FROM_EMAIL'); # email sender
$g_return_path_email = getenv('RETURN_EMAIL');

$tlCfg->exec_cfg->show_testsuite_contents = ENABLED;
$tlCfg->exec_cfg->can_delete_execution = ENABLED;

$tlCfg->results['status_label'] = array(
  "passed" => "test_status_passed",
  "failed" => "test_status_failed",
  "blocked" => "test_status_blocked",
  "not_run" => "test_status_not_run",
  "all" => "test_status_all_status",
  "not_available" => "test_status_not_available",
  "unknown" => "test_status_unknown"
);

$tlCfg->results['status_label_for_exec_ui'] = array(
  "passed" => "test_status_passed",
  "failed" => "test_status_failed",
  "blocked" => "test_status_blocked",
  "not_run" => "test_status_not_run",
  "not_available" => "test_status_not_available",
  "unknown" => "test_status_unknown"
);

$tlCfg->results['default_status'] = "not_run";

$tlCfg->show_realname = TRUE;
$tlCfg->username_format = '%first% %last% [%login%]';
$tlCfg->gui->show_icon_edit = true;
$tlCfg->attachments->action_on_save_empty_title = 'use_filename';

$tlCfg->document_generator->company_name = getenv('COMPANY_NAME');
/** Images are expected in any directory. Be sure to include the complete path from the document root */
$tlCfg->document_generator->company_copyright = getenv('COMPANY_COPYRIGHT');
$tlCfg->document_generator->confidential_msg = getenv('CONFIDENTIAL_MSG');
$tlCfg->document_generator->company_logo = getenv('COMPANY_LOGO');

/** Company logo (used by navigation bar and login page) */
$tlCfg->logo_login = getenv('LOGO_LOGIN');
$tlCfg->logo_navbar = getenv('LOGO_NAVBAR');
$tlCfg->config_check_warning_mode = 'SILENT';

ini_set('session.cache_expire', 54000);
ini_set('session.gc_maxlifetime', 54000);

/**
 * @var string Path to store logs -
 * for security reasons (see http://itsecuritysolutions.org/2012-08-13-TestLink-1.9.3-multiple-vulnerabilities/)
 * put it out of reach via web or configure access denied.
 */
$tlCfg->log_path = '/var/www/html/testlink/logs/'; /* unix example */
$g_repositoryPath = '/var/www/html/testlink/upload_area/'; /* unix example */
?>
