version: '2'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gh_network

  apache:
    build: .
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_TABLE_PREFIX: ${DB_TABLE_PREFIX}
      SMTP_HOST: ${SMTP_HOST}
      THEME_DIR: ${THEME_DIR}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      FROM_EMAIL: ${FROM_EMAIL}
      RETURN_EMAIL: ${RETURN_EMAIL}
      COMPANY_NAME: ${COMPANY_NAME}
      COMPANY_COPYRIGHT: ${COMPANY_COPYRIGHT}
      CONFIDENTIAL_MSG: ${CONFIDENTIAL_MSG}
      COMPANY_LOGO: ${COMPANY_LOGO}
      LOGO_LOGIN: ${LOGO_LOGIN}
      LOGO_NAVBAR: ${LOGO_NAVBAR}
    ports:
      - "80:80"
    volumes:
      - logs:/var/www/html/testlink/logs
      - upload_area:/var/www/html/testlink/upload_area
      - userfiles:/var/www/html/testlink/userfiles
    depends_on:
      mysql:
        condition: service_started
    networks:
      - gh_network

networks:
  gh_network:

volumes:
  db_data:
  logs:
  upload_area:
  userfiles:
